public class Calculator {
    
  
    public integer a {set;get;}
    public integer b {set;get;}
    public integer result {set;get;}
   
         public void sum() 
        { 
                    result=(a+b);
          
        }
        public  void diff()
        { 
            result=(a-b);     
        }
         public void mul()
        { 
            result=(a*b); 
        
        }
        public void div()
        { 
            result=(a/b);
           
        }

       
        

}